### ISSUE TITLE
Consider submitting react scripts to knausj_talon repo?

### ISSUE THREAD

**Issue by trycrmr** [joshwcomeau/talon-commands#1]
Hi! Love your blog post! https://joshwcomeau.com/accessibility/hands-free-coding/ . 

I also work with React and am incorporating your vscode React work into my own Talon user configuration. On the Patreon I received the guidance to open a pull request into the main repo with any additional work that might be useful for others (see screenshot). 
![image](https://user-images.githubusercontent.com/6002123/97465590-9551af00-1918-11eb-93eb-0b7f718fede4.png)

Would you mind if at some point I opened a PR to merge some of the vscode React Talon configs/commands/etc you've put together into the https://github.com/knausj85/knausj_talon/pulls repo?

**Comment by joshwcomeau** [comment]
Hey there,

So I wouldn’t really call my commands “production-ready” - there’s a lot of missing stuff, especially around CSS. I’ve also made some opinionated choices / tailored it around my workflow, not a general React workflow. 

That said, I don’t really mind; if you do, be sure to mention that it’s a long way from feeling complete though.

**Comment by trycrmr** [comment]
Understood!
